### ISSUE TITLE
Add SMS Messaging Via SMSified

### ISSUE THREAD

**Issue by chrismatthieu** [zendeskarchive/broadcast#2]
This gem is awesome!  We would love to work with you on adding outbound SMS notifications to the gem using SMSified.  
Let me know if you have any questions.

Regards,
@ChrisMatthieu

**Comment by marcinbunsch** [comment]
Oh wow this idea is awesome! Thanks for sending it in. I see you've forked - are you planning on implementing it and sending a pull request?

**Comment by chrismatthieu** [comment]
I'll try to add it later this week if time permits.
