### ISSUE TITLE
Subclass?

### ISSUE THREAD

**Issue by trans** [zendeskarchive/broadcast#5]
Wonder why you really need a message subclass. Seems like a nice interface would be a string extension:

```
m = "This is my message".broadcast
m.subject = "Hello"
m.publish(:jabber)
```

Alternate 

```
"This is my message".broadcast do |m|
  m.subject = "Hello"
  m.publish(:jabber)
end
```

Nice library, btw.

**Comment by marcinbunsch** [comment]
That's interesting, I never thought of that. However I don' think it would be good for broadcast to extend the String class. Current API is very separated and does not influence any other classes. There is a branch called mixins I started last night after moonmaster9000's. In this way you can turn any class into a message by including a module. It just might give you the flexibility to do something like you suggested. You can find the discussion here: https://github.com/futuresimple/broadcast/issues/3

**Comment by trans** [comment]
I can understand. You can avoid the core extension with something like:

```
m = Broadcast.message("This is my message")
m.subject = "Hello"
m.publish(:jabber)
```

**Comment by marcinbunsch** [comment]
As we're introducing mixins soon I feel like adding a factory would make the API more complex. What you're suggesting can also be achieved by a simple message subclass:

``` ruby
class GenericJabberMessage < Broadcast::Message

  medium :jabber

  def subject
    options.subject
  end

  def body
    options.body
  end

end

GenericJabberMessage.new(:body => 'This is my message', :subject => 'Hello')
```

To sum up, the idea was to base it on a simple Ruby class to give most versatility when working with broadcast, as I hope the above example illustrates. I feel that adding a factory would be a constraint.

However, I really like your suggestion of being able to specify the media on the fly, by passing them to the publish method. As we can see, the above example does not solve this problem. I'll look into adding that. :)

**Comment by trans** [comment]
You might want to consider "inverting" the design. It's easy to delegate.

``` ruby
    class MyMessage

      def body
        "This is my message"
      end

      def subject
        "Hello"
      end

      def publish(medium, medium_options={})
        m = Broadcast.message(body)
        m.subject = subject
        m.publish(medium, medium_options)
      end

    end
```

Factory is unnecessary.

**Comment by marcinbunsch** [comment]
Actually when I mentioned the factory I was referring to Broadcast.message, which I see as a factory returning (if I'm correct when following your example) Broadcast::Message instances.

The GenericJabberMessage example shows how it would be possible to implement a descendant of Broadcast::Message which would allow specification of the subject and body at a later phase.

The last example you posted, however, is pretty much what the Broadcast::Message is doing right now:

``` ruby
class MyMessage < Broadcast::Message
  def body
    "This is my message"
  end

  def subject
    "Hello"
  end

  # publish comes from Broadcast::Message

end
```

The difference is that right now you cannot specify the medium in the later phase, something I'll look into soon as I really like the idea :) 

I think that would give you the flexibility of providing the target media right before publishing (for example when you don't know what they will be before, so you can't specify them in the class).

So all you would have to do to use it would be (let's assume we have a Broadcast::Message::Simple which has a similar implementation to the aforementioned GenericJabberMessage, so accepts a :body and :subject in the constructor, but also allows for the media to be supplied as an argument to #publish)

``` ruby
message = Broadcast::Message::Simple(:body => "This is my message", :subject => "Hello!")
message.publish(:jabber, :irc)
```

This solution would allow dynamic creation of messages with dynamic media selection and be consistent with current Broadcast API.

**Comment by trans** [comment]
A factory method is something that instantiates a new class, rather than an object. The point I'm basically making is that your API requires the creation of class when an object is all that is really needed. You're API really could be quite a bit simpler and provide all the same functionality.

**Comment by ghost** [comment]
Not everything needs to be an 'API'. Inheritance is a perfectly valid way of providing functionality. The problem though is Ruby's single inheritance. It restricts what you can do via inheritance, eg. making an existing object broadcast-able. That's why a mixin approach is probably more useful. Maybe something like...

``` ruby
class MyClass < SuperClass
  broadcastable :jabber, :irc

  def subject
  end

  def body
  end
...
```
