### ISSUE TITLE
Exception when exceptions are raised

### ISSUE THREAD

**Issue by ghost** [zendeskarchive/broadcast#8]
While I was testing my Tumblr medium I kept hitting the following exception

``` ruby
'/Users/henry/Development/Ruby/Code/broadcast/lib/broadcast/simple.rb:17:in `[]': can't convert Symbol into Integer (TypeError)'

simple.rb:17      Broadcast.logger.error "Publishing of #{self.class.name} to #{medium[:name]} failed:\n#{$!}"

```

The problem is 'medium' is a symbol. What's is supposed to happen here?

**Comment by marcinbunsch** [comment]
I merged in Broadcast::Message::Simple in 0.3.0 and this bug is fixed, thanks for reporting it!
