### ISSUE TITLE
Issue with string keys in Mail delivery_options

### ISSUE THREAD

**Issue by lyleunderwood** [zendeskarchive/broadcast#9]
I'm not sure if this is an issue in Mail or not, but I'm using Mail version 2.2.15. Broadcast is giving Mail a Hashie::Mash for delivery_options which seems to serialize to a hash with string keys. Mail appears to be expecting symbol keys. The result is that for example SMTP delivery options are not used by Mail when configured through Broadcast.

I fixed this for myself with a monkeypatch to Hashie::Mash, but as I doubt this is a proper solution, I have not issued a pull request:

lyleunderwood/broadcast@afdd780

**Comment by marcinbunsch** [comment]
Hi

This commit addresses this issue:
https://github.com/futuresimple/broadcast/commit/0d621714821f8c58ecc68ec0bc4ae753411d114d

It is in broadcast >= 0.2.3 

Thanks for reporting the issue, and sorry it took me so long to implement :)
